###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker build csharp
      run: |
        docker build ./boat-backend -t abouadam/boat-backend:1.0.0
    - name : docker push
      run : docker push abouadam/boat-backend:1.0.0

