# This is a basic workflow to help you get started with Actions

name: CI

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     - name : docker build csharp
       run: |
          docker build ./c# -t aimvector/csharp:1.0.0
      # Runs a single command using the runners shell
      - name: docker push
        run: |
          docker push abouadam/csharp:1.0.0
